name: Check Branch Name

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - "*"

jobs:
  check-branch-name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check Branch Name
        run: |
          branch_name=$(echo "${{ github.ref }}" | sed 's#refs/heads/##')
          #branch_name=$(git symbolic-ref --short HEAD)
          if [[ "$branch_name" =~ ^feature/.*$ ]]; then
            echo "Branch name is valid: $branch_name"
          else
            echo "Branch name is invalid: $branch_name"
            exit 1
          fi
