name: Bump version
on:
  push:
    branches:
      - "release*"
env:
  SEMVER_FILE_NAME: 'package.json'

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: test-instance

    steps:
      - uses: actions/checkout@master

      - name: echo package.json
        id: read-version
        env:
          CHECK_ENV: ${{ secrets.CHECK_ENV }}
        run: |
          RELEASE_VERSION=`grep -m1 version ${{ env.SEMVER_FILE_NAME }} | awk -F: '{ print $2 }' | sed 's/[ ",]//g'` 
          echo version=$RELEASE_VERSION >> $GITHUB_OUTPUT
          echo ${{secrets.CHECK_ENV}} | sed 's/./& /g'

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          RELEASE_BRANCH: ${{ github.head_ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ steps.read-version.outputs.version }}
          release_name: Release $RELEASE_BRANCH
          draft: false
          prerelease: false