name: Bump version
on:
  push:
    branches:
      - "release*"
env:
  SEMVER_FILE_NAME: 'package.json'

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: test-instance

    steps:
      - uses: actions/checkout@master

      - name: echo package.json
        id: read-version
        env:
          CHECK_ENV: ${{ secrets.CHECK_ENV }}
        run: |
          RELEASE_VERSION=`grep -m1 version ${{ env.SEMVER_FILE_NAME }} | awk -F: '{ print $2 }' | sed 's/[ ",]//g'` 
          echo version=$RELEASE_VERSION >> $GITHUB_OUTPUT
          echo ${{secrets.CHECK_ENV}} | sed 's/./& /g'

      - uses: "marvinpinto/action-automatic-releases@latest"
        env:
          RELEASE_VERSION: ${{ steps.read-version.outputs.version }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v$RELEASE_VERSION"
          prerelease: true
          title: "Release $GITHUB_BRANCH"
          files: |